name: Check Modified Files

on: [push]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for modified files
        run: |
          git diff --name-only --exit-code
          if [ $? -eq 0 ]; then
            echo "No files have been modified."
          else
            echo "Some files have been modified."
          fi