#name: Check Modified Files
##
##on:
##  pull_request:
##
##jobs:
##  check:
##    runs-on: ubuntu-22.04
##    timeout-minutes: 15
##
##    steps:
##      - name: Checkout
##        uses: actions/checkout@v4
##
##
##        # ここまではあっていそう。
##
##      - name: Check for modified files
##        run: |
##          git diff --name-only --exit-code
##          if [ $? -eq 0 ]; then
##        # 変更されたファイルが存在しない場合
##            echo "No files have been modified."
##          else
##        # 変更されたファイルが存在する場合
##            echo "Some files have been modified."
##          fi
#
#
#on:
#  pull_request:
#
#jobs:
#  check:
#    runs-on: ubuntu-22.04
#    timeout-minutes: 15
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Check for modified files
#        run: |
#          git diff --name-only --exit-code
#        continue-on-error: true


name: Check Modified Files

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-22.04
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Check for modified files
        run: |
          if  git diff --name-only --exit-code
          then
            exit 1
          fi